### PR TITLE
Plone 4.3 compatibility

### PR DESCRIPTION
**Pull request by ghost**
From vanilla Plone 4.3 zope.app.component is missing, causing portlet to fail to run. Added the dependency, and it seems to fix the compatibility.

### CODE REVIEW

**Comment by davisagli** [comment]
This should be imported from zope.component.hooks for Plone 4.3. We don't want to pull in all the zope.app.\* packages unnecessarily.

**Comment by ghost** [comment]
Thanks for the tip, smaller risks when not pulling in all kinds of unnecessary stuff. Adjusted the dependency accordingly.

**Comment by ghost** [comment]
... except that you can't just add that to setup.py it seems, won't work. That's either wrong method or I'm an idiot.

**Comment by davisagli** [comment]
I didn't mean add zope.component.hooks as a dependency. It's not actually a distribution available on PyPI; it comes with Zope2. I meant you need to change the code where zope.app.component is imported.

**Comment by ghost** [comment]
Well, I learned something new here. (About some Plone/Zope internals and how to use git when you have screwed up.)

I tested around a bit more, and the unreleased version already has the changes required to run on 4-2/4.3. There is no need for code changes, but there is a need for someone to check the current version and make a proper release.

**Comment by khink** [comment]
@Cuidightheach I see no code changes since last release. Your pull request can't be automatically merged, so there's something in there please mess around with git some more :) so your fork can be merged. I can make a release then.

**Comment by ghost** [comment]
Well, something is wrong here.

Starting with completely clean Plone 4.3 installation. Collective.portlet.content to buildout, and it picks 1.7: 

```
*************** PICKED VERSIONS ****************
[versions]
collective.portlet.content = 1.7
```

After that bin/plonectl fg:

```
File "/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 179, in resolve
mod = __import__(mname, *_import_chickens)
File "/usr/local/Plone/buildout-cache/eggs/collective.portlet.content-1.7-py2.7.egg/collective/portlet/content/contentportlet.py", line 9, in <module>
from zope.app.component.hooks import getSite
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/usr/local/Plone/zinstance/parts/instance/etc/site.zcml", line 15.2-15.55
ZopeXMLConfigurationError: File "/usr/local/Plone/zinstance/parts/instance/etc/package-includes/002-collective.portlet.content-configure.zcml", line 1.0-1.70
ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/collective.portlet.content-1.7-py2.7.egg/collective/portlet/content/configure.zcml", line 38.5-47.11
ImportError: No module named component.hooks
```

Taking a look at mentioned /usr/local/Plone/buildout-cache/eggs/collective.portlet.content-1.7-py2.7.egg/collective/portlet/content/contentportlet.py shows that the pulled 1.7 has older version of the file than git. The new version works instantly when I pull it to src/ and run with the develop stanza. They seem to have quite a few differences.

**Comment by khink** [comment]
Sorry, i had that all wrong. There were code changes and a new release should fix it. Thanks for pointing this out!

**Comment by khink** [comment]
Release is done.

**Pull request closed without merging**
